name: dus_dashboard
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  shared_preferences: ^2.2.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  google_fonts: ^5.1.0
  font_awesome_flutter: ^10.5.0
  line_awesome_flutter: ^2.0.0
  shimmer: ^3.0.0
  permission_handler: ^10.4.3
  permission_handler_web: ^0.0.2
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  http: ^1.1.0
  http_parser: ^4.0.2
  intl: ^0.18.1
  dartz: ^0.10.1
  flutter_rating_bar: ^4.0.1
  flutter_credit_card: ^3.0.7
  adaptive_theme: ^3.3.0
  collection: ^1.17.2
  gap: ^3.0.1
  go_router: ^10.1.0
  intersperse: ^2.0.0
  recase: ^4.1.0
  responsive_framework: ^1.1.0
  simple_logger: ^1.9.0+2
  two_dimensional_scrollables: ^0.0.1
  elegant_notification: ^1.11.0
  url_launcher: ^6.1.12
  badges: ^3.0.2
  flip_panel_plus: ^1.0.0+3
  cached_network_image: ^3.2.3
  animate_gradient: ^0.0.2
  gradient_borders: ^1.0.0
  dynamic_color: ^1.6.8
  window_manager: ^0.3.7
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  currency_text_input_formatter: ^2.1.10
  dropdown_button2: ^2.3.8
  file_picker: ^5.2.6
  desktop_drop: ^0.4.4
  auto_size_text: ^3.0.0
  data_table_2: ^2.5.9
  cross_file: ^0.3.3+7
  cross_file_image: ^1.1.0
  animations: ^2.0.8
  carousel_slider: ^4.2.1
  syncfusion_flutter_core: ^22.2.10
  syncfusion_flutter_charts: ^22.2.10
  syncfusion_flutter_calendar: ^22.2.10
  syncfusion_flutter_datepicker: ^22.2.10
  syncfusion_flutter_datagrid: ^22.2.10
  form_builder_phone_field: ^2.0.1
  form_builder_extra_fields: ^10.1.0
  form_builder_file_picker: ^4.1.0
  form_builder_image_picker: ^4.0.0
  flutter_screenutil: ^5.9.0
  simple_animations: ^5.0.2
  flutter_animate: ^4.5.0
  particles_flutter: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  go_router_builder: ^2.3.0
  build_verify: ^3.1.0
  pedantic_mono: ^1.23.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/
   - assets/flags/
   - assets/svg/
   - assets/animation/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
